version: '2'
services:
  mongodb:
    image: akisys/mongodb-cluster:3.4
    environment:
      MONGO_PORT: 27017
      MONGO_STARTUP: mongodb
      MONGO_SERVICE_ID: mongodb
      MONGO_REPLSET: mongodb-rs1

