version: '2'
services:
  mongoshardcfg:
    image: akisys/mongodb-cluster:3.4
    environment:
      MONGO_PORT: 27017
      MONGO_STARTUP: mongodb
      MONGO_SERVICE_ID: mongoshardcfg
      MONGO_REPLSET: configReplSet
      MONGO_SVR: configsvr
  mongoshardnode:
    image: akisys/mongodb-cluster:3.4
    environment:
      MONGO_PORT: 27017
      MONGO_STARTUP: mongodb
      MONGO_SERVICE_ID: mongoshardnode
      MONGO_REPLSET: mongodb-rs1
      MONGO_SVR: shardsvr
      MONGO_SHARDADD_SERVICE_ID: mongos
  mongos:
    image: akisys/mongodb-cluster:3.4
    environment:
      MONGO_PORT: 27017
      MONGO_STARTUP: mongos
      MONGO_SERVICE_ID: mongoshardcfg
      MONGO_REPLSET: configReplSet
